# -*- coding: utf-8 -*-
"""Latihan Modul 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOEHXpGHPjV1f_HlKD01bRCMm2jKt4uA
"""

uang = 0
print('duit gua = ',uang)

duit = 100000
print ('sapet duit =', duit)

uang += duit
print ('Duit gua karang =', uang)

WeUp = 30000
uang += jajan
print ('Duit gua karang, abis jajan =', uang)

if uang < 100000:
  print('Ey get yo money up, not yo funny up')
elif uang == 100000:
  print('Aight u str8')
else:
  print('bagus atau parah gak tau gua')

# Roulette Wheel
import random

List = ['akbar','ell','alifa','bahar','alfin','affan']
ok = random.randint(0,5)
print(List[ok])

import random
hari = 1
while True:
  mendung = [500,1000,700,1500,2000]
  Random = random.randint(0,4)
  tingdung = mendung[Random]
  LuLam = 2
  tolux = random.randint(100,25000)
  Intensitas = tolux/LuLam - tingdung

  print('Hari ke-', hari)
  print("intensitas cahaya = ",Intensitas)
  if Intensitas >= 10000:
    print('sekarang sedang cerah\nLampu = Mati')
  elif Intensitas < 10000 and Intensitas > 800:
    print('Agak gelap sekarang, tapi gpp\nLampu = Mati')
  elif Intensitas < 800:
    print('Gelap nyoo\nLampu = Nyala')
  IN = (input('Mau cek lagi?'))
  hari += 1
  if IN == 'tidak':
    break

def smt_3_pagi():
  print('akbar')
  print('kenzi')
  print('udin')

smt_3_pagi()

a = 1
b = 6

if a == 1 and b == 2:
  print('eyy carambaa')
else:
  print('貴様')
space = 7
nomor = 9
for i in range(space):
  # print('akbar'*i)
  print('❤️'*i)
  space -= 1

nama= ['Akbar','Kenzi','Bahar','Rafi','Alfin']
nilaiA= [80,70,50,70,90]
nilaiB = [70,70,100,74,85]
u = 0
rataA = sum(nilaiA)/5
rataB = sum(nilaiB)/5
# print(rata_A,'dan', rata_B)

for i in (nama):
  rataper = nilaiA[u] + nilaiB[u] / 2

  print('Nilai',nama[u],'adalah',nilaiA[u],'dan',nilaiB[u])

  if nilaiA[u] >= rataA and nilaiB[u] >= rataB:
    print('Mahasiswa',nama[u],'dinyatakan lulus dengan rata-rata',rataper)
  else:
    print('Mahasiswa',nama[u],'dinyatakan tidak lulus dengan rata-rata',rataper,'\n')

  u += 1